"""create chargeback cases

Revision ID: c3b00ffe7204
Revises: 
Create Date: 2026-09-28 23:54:50.192589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3b00ffe7204'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chargeback_cases',
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('stripe_dispute_id', sa.String(length=255), nullable=False),
    sa.Column('dispute_reason', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('open', 'gathering_evidence', 'waiting_for_human', 'submitted', 'waiting_for_stripe', 'won', 'lost', 'closed', name='case_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('case_id')
    )
    op.create_index(op.f('ix_chargeback_cases_stripe_dispute_id'), 'chargeback_cases', ['stripe_dispute_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chargeback_cases_stripe_dispute_id'), table_name='chargeback_cases')
    op.drop_table('chargeback_cases')
    # ### end Alembic commands ###
